codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

comment:
  layout: "header, diff, flags, files"
  behavior: default
  require_changes: no
  require_base: yes
  require_head: yes
